export const SET_LOADING = 'SET_LOADING'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const SET_USER = 'SET_USER'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR'
export const FETCH_SINGLE_TASK_SUCCESS = 'FETCH_SINGLE_TASK_SUCCESS'
export const FETCH_SINGLE_TASK_ERROR = 'FETCH_SINGLE_TASK_ERROR'

export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS'
export const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR'